language: cpp
sudo: required
matrix:
  include:
   - os: linux
     compiler: gcc
     addons:
       apt:
         sources:
         - ubuntu-toolchain-r-test
         - george-edison55-precise-backports
         packages:
         - cmake
         - cmake-data
         - g++-4.9
     env: CXX_COMPILER='g++-4.9'
install:
  - cmake -version
script:
  - cmake -H. -Bbuild -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_BUILD_TYPE=Release
  - cd build && make
  - ctest
  - cat Testing/Temporary/LastTest.log
